"""UI strings (resource table). Russian is the primary language; i18n-ready by key."""

from __future__ import annotations

RU: dict[str, str] = {
    "app_title": "AI-ассистент приёма",
    "draft_banner": "Черновик — проверьте перед внесением в медицинскую карту.",
    "start": "🎙  Начать приём",
    "stop": "■  Завершить",
    "cancel": "Отменить",
    "recording": "● Идёт приём",
    "segments": "Распознано фрагментов: {n}",
    "mic_label": "Микрофон:",
    "mic_default": "Системный по умолчанию",
    "refresh": "Обновить",
    "finalizing": "Завершаю распознавание…",
    "finalizing_n": "Завершаю распознавание… {done} из {total}",
    "analyzing": "Формирую жалобы и анамнез…",
    "complaints": "ЖАЛОБЫ",
    "history": "АНАМНЕЗ ЗАБОЛЕВАНИЯ",
    "copy": "Копировать",
    "copy_all": "Копировать всё",
    "copy_transcript": "Копировать расшифровку",
    "show_transcript": "Показать расшифровку",
    "new_visit": "Новый приём",
    "retry_analysis": "Повторить анализ",
    "check": "ПРОВЕРИТЬ",
    "show_source": "Показать источник",
    "source_title": "Источник в расшифровке",
    "no_source": "Для выделенного фрагмента источник не найден (текст мог быть изменён вручную).",
    "copied_complaints": "Жалобы скопированы",
    "copied_history": "Анамнез скопирован",
    "copied_all": "Жалобы и анамнез скопированы",
    "copied_transcript": "Расшифровка скопирована",
    "nothing_to_copy": "Нечего копировать",
    "confirm_new_visit": "Начать новый приём? Нескопированные изменения будут удалены.",
    "model_ready": "GigaAM ● Готов",
    "model_ready_device": "GigaAM ● Готов ({device})",
    "model_download": "GigaAM: скачивание модели… {pct}%",
    "model_download_start": "GigaAM: подготовка к скачиванию модели…",
    "model_loading": "GigaAM: загрузка модели…",
    "model_error": "GigaAM ● Ошибка",
    "retry": "Повторить",
    "cloud_on": "Для формирования документа используется облачная модель.",
    "cloud_local": "Документ формируется локальной моделью ИИ.",
    "ai_off": "ИИ не настроен — будет доступна только расшифровка.",
    "ai_ready": "ИИ ● Готов",
    "ai_not_ready": "ИИ ● Не настроен",
    "placeholder_complaints": "Недостаточно данных для формирования жалоб.",
    "placeholder_history": "Недостаточно данных для формирования анамнеза.",
    "low_level": "Слишком тихий сигнал микрофона — проверьте выбранный микрофон.",
    "lagging": "Распознавание отстаёт от речи; оно завершится после окончания приёма.",
    "settings": "Настройки",
    "hotkeys_hint": "Ctrl+Alt+R — начать/завершить, Ctrl+Alt+1/2 — копировать",
    "dev_open_wav": "Открыть аудиофайл…",
    "dev_paste": "Вставить расшифровку…",
    "dev_paste_title": "Анализ вставленной расшифровки",
    "dev_paste_hint": "Каждая строка — отдельный фрагмент расшифровки.",
    "analyze": "Анализировать",
    "transcript_title": "Расшифровка приёма",
    "tray_show": "Показать",
    "tray_start": "Начать приём",
    "tray_quit": "Выход",
    "crash": "Произошла техническая ошибка. Текущий текст не был отправлен или сохранён.",
    "already_running": "Приложение уже запущено.",
    # errors (code -> text)
    "err_microphone_unavailable": "Микрофон недоступен. Проверьте подключение и выбор микрофона.",
    "err_microphone_permission": "Нет доступа к микрофону. Разрешите доступ: Параметры Windows → Конфиденциальность → Микрофон.",
    "err_microphone_lost": "Микрофон отключён во время приёма. Распознанный текст сохранён.",
    "err_model_unavailable": "Модель распознавания ещё не готова.",
    "err_model_download_failed": "Не удалось скачать модель GigaAM. Проверьте подключение к интернету и нажмите «Повторить».",
    "err_not_enough_disk": "Недостаточно места на диске для модели GigaAM (нужно около 1 ГБ).",
    "err_model_checksum": "Файл модели повреждён и удалён. Нажмите «Повторить», чтобы скачать заново.",
    "err_model_storage": "Нет доступа к папке моделей. Проверьте права доступа.",
    "err_gigaam_load_failed": "Не удалось загрузить модель GigaAM.",
    "err_stt_failed": "Ошибка распознавания речи.",
    "err_llm_unavailable": "Распознавание завершено. Для формирования документа требуется подключение к AI.",
    "err_llm_not_configured": "Распознавание завершено. Для формирования документа требуется подключение к AI (Настройки → ИИ).",
    "err_invalid_credentials": "Неверный API-ключ ИИ. Проверьте настройки.",
    "err_timeout": "ИИ не ответил вовремя. Расшифровка сохранена — можно повторить анализ.",
    "err_invalid_structured_response": "Не удалось сформировать структурированный документ. Расшифровка доступна.",
    "err_cancelled": "Анализ отменён. Расшифровка доступна.",
    "err_internal_error": "Произошла техническая ошибка. Текущий текст не был отправлен или сохранён.",
    "err_cancelled_download": "Скачивание модели отменено.",
}


def tr(key: str, **kwargs: object) -> str:
    text = RU.get(key, key)
    return text.format(**kwargs) if kwargs else text


def error_text(code: str) -> str:
    return RU.get(f"err_{code}", RU["err_internal_error"])
